--- !ditz.rubyforge.org,2008-03-06/issue 
title: test_large_with_exclusions is broken
desc: |-
  There is something wrong with comparing two large dicts.
  Tried to fix it by using odict instead, but it doesn't seem to help.
type: :bugfix
component: json_diff
release: 
reporter: Matej Cepl <mcepl@redhat.com>
status: :closed
disposition: :fixed
creation_time: 2011-11-08 18:05:08.687378 Z
references: []

id: fb675aa395503fb3e4fdbcd2ab22da02f4345d47
log_events: 
- - 2011-11-08 18:05:10.458418 Z
  - Matej Cepl <mcepl@redhat.com>
  - created
  - ""
- - 2011-11-20 00:01:51.232208 Z
  - Matej Cepl <mcepl@redhat.com>
  - closed with disposition fixed
  - Fixed ... nothing to do with odict, fortunately.
